apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: testspring 
  janus-idp.io/tekton: testspring
  backstage.io/kubernetes-id: testspring
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: testspring
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  