apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: testspring
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: testspring 
  name: testspring
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: testspring
    weight: 100 
