apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: testspring
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: testspring 
  name: testspring
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: testspring 
